[context.branch-deploy.environment]
NODE_ENV = "production"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200


[[headers]]
for = "/*"
[headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  Referrer-Policy = "no-referrer"
  X-Content-Type-Options = "nosniff"
